### PR TITLE
BF: typo fixed in angularFire.Firebase type annotation

### PR DESCRIPTION
**Pull request by petrusek**
On lines 54 and 60 I've got: WARNING - Bad type annotation. Unknown type angularFire.Firebase
I guess it was just a typo.

### CODE REVIEW

**Comment by isabo** [comment]
Thanks! It's weird that I don't get the same warning when I compile.

**Comment by petrusek** [comment]
It probably showed up when I've set warning_level to VERBOSE. (I thank you for creating those files :+1: )

**Comment by isabo** [comment]
I also use verbose. Could it be that the type is only checked if the code actually makes use of the promise resolve() argument?

**Comment by petrusek** [comment]
No idea :-), I've been experimenting a lot, so I can't confirm when and what exactly triggered it. I'm using gulp-closure-compiler, which might set some other options too, but I'm not sure.
It might be possible that it is some version mismatch, because the old Firebase library used that type (I think).

**Pull request merged**
